services:
  web:
    container_name: 'd2mp-web-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:80'
    environment:
      - D2MP_DB_CONN_STRING=${D2MP_DB_CONN_STRING}
      - D2MP_STEAM_API_KEY=${D2MP_STEAM_API_KEY}
      - D2MP_BASIC_AUTH_SECRET=${D2MP_BASIC_AUTH_SECRET}
    volumes:
      - /etc/letsencrypt/live/metaparty.tips:/https:ro
    depends_on:
      - 'postgres'
    networks:
      - d2mp-network  

  postgres:
    container_name: d2mp-postgresql
    ports:
      - '5433:5433'
    environment:
      - POSTGRES_PASSWORD=${D2MP_DB_PASSWORD}
    volumes:
      - 'd2mp-postgresql-volume:/var/lib/postgresql/data'
    image: 'postgres:latest'
    networks:
      - d2mp-network
    command: -p 5433

volumes:
  d2mp-postgresql-volume:

networks:
  d2mp-network: